### register request
POST  http://localhost:8585/auth/register
Content-Type: application/json

{
    "username":"mahdisherafat",
    "email":"alia@ali.com",
    "mobile":"09162517729",
    "password":"123456",
    "confirm_password":"123456"
    
}